server:
  port: 7785

spring:
  application:
    name: spider

#  ai:
#    openai:
#      api-key: sk-54034f01de884cfba1a05679d441e51f
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/
#      chat:
#        options:
#          model: qwen-plus
#        completions-path: /v1/chat/completions

#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen2.5:7b
#          temperature: 0.1

  ai:
    openai:
      api-key: "no-key"
      base-url: http://10.47.11.31:8000
      chat:
        options:
          model: /home/worker/project/LLaMA-Factory/saves/Qwen3-1.7B-Instruct/export_model_1030/
        completions-path: /v1/chat/completions